# -*- coding: utf-8 -*-
"""CodeAlpha_Handwritten Character Recognisation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uIaVUiTfLouNbBcVHp_q4XQQh7iPRDPX
"""

import zipfile
import os

zip_file_path = '/content/archive (2).zip'
extract_dir = '/content/handwritten_characters'

# Create the extraction directory if it doesn't exist
os.makedirs(extract_dir, exist_ok=True)

# Unzip the file
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    zip_ref.extractall(extract_dir)

print(f"Dataset unzipped to: {extract_dir}")

# List the contents of the extracted directory to understand the structure
print("Contents of the extracted directory:")
for root, dirs, files in os.walk(extract_dir):
    level = root.replace(extract_dir, '').count(os.sep)
    indent = ' ' * 4 * (level)
    print(f"{indent}{os.path.basename(root)}/")
    subindent = ' ' * 4 * (level + 1)
    for f in files[:5]: # Print only first 5 files in each directory for brevity
        print(f"{subindent}{f}")
    if len(files) > 5:
        print(f"{subindent}...(and {len(files) - 5} more files)")

import pandas as pd

# Define paths to the CSV files
train_csv_path = os.path.join(extract_dir, 'mnist_train.csv')
test_csv_path = os.path.join(extract_dir, 'mnist_test.csv')

# Load the datasets
train_df = pd.read_csv(train_csv_path)
test_df = pd.read_csv(test_csv_path)

print("Training data shape:", train_df.shape)
print("Test data shape:", test_df.shape)

print("\nFirst 5 rows of the training data:")
print(train_df.head())

print("\nFirst 5 rows of the test data:")
print(test_df.head())

import numpy as np

# Separate features (X) and labels (y)
X_train = train_df.drop('label', axis=1).values
y_train = train_df['label'].values

X_test = test_df.drop('label', axis=1).values
y_test = test_df['label'].values

# Reshape image data to 28x28 pixels
# MNIST images are 28x28 grayscale images. The '1' indicates a single color channel.
X_train = X_train.reshape(-1, 28, 28, 1)
X_test = X_test.reshape(-1, 28, 28, 1)

# Normalize pixel values to a range of 0 to 1
X_train = X_train / 255.0
X_test = X_test / 255.0

print("Shape of X_train after reshaping and normalization:", X_train.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of X_test after reshaping and normalization:", X_test.shape)
print("Shape of y_test:", y_test.shape)

# Display a sample image and its label to verify
import matplotlib.pyplot as plt

plt.figure(figsize=(2, 2))
plt.imshow(X_train[0].reshape(28, 28), cmap='gray')
plt.title(f"Label: {y_train[0]}")
plt.axis('off')
plt.show()

import tensorflow as tf
from tensorflow.keras import layers, models

# Define the CNN model
model = models.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    layers.Conv2D(64, (3, 3), activation='relu'),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax') # 10 classes for digits 0-9
])

# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Display model summary
model.summary()

# Train the model
history = model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

print("\nModel training complete.")

print("\nEvaluating the model on the test data...")
loss, accuracy = model.evaluate(X_test, y_test, verbose=2)

print(f"Test Loss: {loss:.4f}")
print(f"Test Accuracy: {accuracy:.4f}")